print("hello world is how you say hello world in English")
print("Geiá sou Kósme is how you say hello world in Greek")
print("Olá Mundo is how you say hello world in Portuguese")
print("Ahoj světe is how you say hello world in Czech")
print("annyeong sesang is how you say hello world in Korean")
print("Nǐ hǎo, shìjiè is how you say hello world in Chinese")
print("Namaste duniya is how you say hello world in Hindi")
print("Halo Dunya is how you say hello world in Swahili")
print("שלום עולם is how you say hello world in Hebrew")
print("مرحبا بالعالم is how you say hello world in Arabic")
