print("Row" + " your boat")
print("Gently down the stream.")
print("Merrily")
print("Life is but a dream.")
print()
print()
print("And I was like")
print("Baby")
print("oooooooh!")
print("Baby")
print("nooooooo!")
